import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/header";
import Footer from "@/Components/footer";

export const metadata: Metadata = {
  title: "Multi-Step Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
